In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

`np.nan 是非数字`  
`这里通过传递一个list对象类创建一个Series，同时pandas默认创建整型索引`

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [3]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
s.shape

(6,)

In [13]:
# 创建一个DataFrame
dates = pd.date_range('20130101', periods=6)
print(type(dates))
dates

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [14]:
lis = np.random.randn(6, 4)
print(lis)
df = pd.DataFrame(lis, index=dates, columns=list('ABCD'))

[[-0.43956847  0.48582664 -0.14249448  0.76819718]
 [ 0.60665401 -0.00348119 -0.71425222  1.92218174]
 [-0.23225863 -0.01519794 -0.41644336  0.89660058]
 [ 0.83425654  0.36994682 -0.08387205  1.08089037]
 [-0.09792805 -0.00354183 -0.12989991  1.69773261]
 [ 1.79605304  2.09522976 -0.15232828  0.16499465]]


In [15]:
# 定义DataFrame时，使用index给行索引赋值，columns给列索引赋值
df

A         B         C         D
2013-01-01 -0.439568  0.485827 -0.142494  0.768197
2013-01-02  0.606654 -0.003481 -0.714252  1.922182
2013-01-03 -0.232259 -0.015198 -0.416443  0.896601
2013-01-04  0.834257  0.369947 -0.083872  1.080890
2013-01-05 -0.097928 -0.003542 -0.129900  1.697733
2013-01-06  1.796053  2.095230 -0.152328  0.164995

In [25]:
b = pd.Timestamp('20130102')
print(b)
print(type(b))
print('-' * 20)
# this 1 -> [1, 1, 1, 1]
c = pd.Series(1, index=list(range(4)), dtype='float32')
print(c)
print(type(c))
print('-' * 20)
# [3]*4 -> [3, 3, 3, 3]
d = np.array([3]*4, dtype='int32')
print(d)
print(type(d))
print('-' * 20)
e = pd.Categorical(['test', 'train', 'test', 'train'])
print(e)
print(type(e))
print('-' * 20)

2013-01-02 00:00:00
<class 'pandas._libs.tslib.Timestamp'>
--------------------
0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32
<class 'pandas.core.series.Series'>
--------------------
[3 3 3 3]
<class 'numpy.ndarray'>
--------------------
[test, train, test, train]
Categories (2, object): [test, train]
<class 'pandas.core.categorical.Categorical'>
--------------------


In [26]:
# 给 DataFrame 列的值可以为 list，Timestamp，Series，ndarray，Categorical 类型
dic = {
    'A': 1.,
    'B': b,
    'C': c,
    'D': d,
    'E': e,
    'F': 'foo'
}
df2 = pd.DataFrame(dic)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [28]:
# 查看每一列的数据类型
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [29]:
df

A         B         C         D
2013-01-01 -0.439568  0.485827 -0.142494  0.768197
2013-01-02  0.606654 -0.003481 -0.714252  1.922182
2013-01-03 -0.232259 -0.015198 -0.416443  0.896601
2013-01-04  0.834257  0.369947 -0.083872  1.080890
2013-01-05 -0.097928 -0.003542 -0.129900  1.697733
2013-01-06  1.796053  2.095230 -0.152328  0.164995

In [34]:
df.head()

A         B         C         D
2013-01-01 -0.439568  0.485827 -0.142494  0.768197
2013-01-02  0.606654 -0.003481 -0.714252  1.922182
2013-01-03 -0.232259 -0.015198 -0.416443  0.896601
2013-01-04  0.834257  0.369947 -0.083872  1.080890
2013-01-05 -0.097928 -0.003542 -0.129900  1.697733

In [32]:
df.tail(3)

A         B         C         D
2013-01-04  0.834257  0.369947 -0.083872  1.080890
2013-01-05 -0.097928 -0.003542 -0.129900  1.697733
2013-01-06  1.796053  2.095230 -0.152328  0.164995

In [35]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [37]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.411201  0.488130 -0.273215  1.088433
std    0.840483  0.816517  0.246219  0.641643
min   -0.439568 -0.015198 -0.714252  0.164995
25%   -0.198676 -0.003527 -0.350415  0.800298
50%    0.254363  0.183233 -0.147411  0.988745
75%    0.777356  0.456857 -0.133049  1.543522
max    1.796053  2.095230 -0.083872  1.922182

In [38]:
# 转置
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.439568    0.606654   -0.232259    0.834257   -0.097928    1.796053
B    0.485827   -0.003481   -0.015198    0.369947   -0.003542    2.095230
C   -0.142494   -0.714252   -0.416443   -0.083872   -0.129900   -0.152328
D    0.768197    1.922182    0.896601    1.080890    1.697733    0.164995

In [48]:
# 对轴进行排序 axis 影响列索引 ascending 影响行索引 正序倒序
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  0.768197 -0.142494  0.485827 -0.439568
2013-01-02  1.922182 -0.714252 -0.003481  0.606654
2013-01-03  0.896601 -0.416443 -0.015198 -0.232259
2013-01-04  1.080890 -0.083872  0.369947  0.834257
2013-01-05  1.697733 -0.129900 -0.003542 -0.097928
2013-01-06  0.164995 -0.152328  2.095230  1.796053

In [57]:
# 按值进行排序
df.sort_values(by=['B'])

A         B         C         D
2013-01-03 -0.232259 -0.015198 -0.416443  0.896601
2013-01-05 -0.097928 -0.003542 -0.129900  1.697733
2013-01-02  0.606654 -0.003481 -0.714252  1.922182
2013-01-04  0.834257  0.369947 -0.083872  1.080890
2013-01-01 -0.439568  0.485827 -0.142494  0.768197
2013-01-06  1.796053  2.095230 -0.152328  0.164995