In [1]:
import torch

In [ ]:
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.password = "sha1:c718891c46fa:0099243e142234db1e85e36aa08110566b2967a6"
c.NotebookApp.token = ""
c.NotebookApp.notebook_dir = "workspace"

In [9]:
y_hat = torch.tensor([[0.1, 0.5, 0.3], [0.1, 0.2, 0.3], [0.6, 0.2, 0.3]])
y_hat

tensor([[0.1000, 0.5000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.6000, 0.2000, 0.3000]])

In [10]:
torch.argmax(y_hat, dim=1)

tensor([1, 2, 0])

In [11]:
y = torch.tensor([0, 2, 0])
ytorch.tensor([0, 2, 0])

tensor([0, 2, 0])

In [12]:
torch.argmax(y_hat, dim=1) == y

tensor([False,  True,  True])

In [13]:
torch.sum(torch.argmax(y_hat, dim=1) == y)

tensor(2)

In [15]:
torch.sum(torch.argmax(y_hat, dim=1) == y).float()

tensor(2.)

In [14]:
(torch.sum((torch.argmax(y_hat, dim=1) == y))).float()

tensor(2.)

In [18]:
y.long().dtype

torch.int64

In [19]:
y.dtype

torch.int64

In [20]:
torch.tensor([0, 2, 0]).dtype

torch.int64

In [27]:
y.float().mean(dim=0, keepdim=True)

tensor([0.6667])

softmax运算符（softmax operator）解决了以上两个问题。它通过下式将输出值变换成值为正且和为1的概率分布：

$$
 \hat{y}_1, \hat{y}_2, \hat{y}_3 = \text{softmax}(o_1, o_2, o_3) 
$$

其中

$$
 \hat{y}1 = \frac{ \exp(o_1)}{\sum_{i=1}^3 \exp(o_i)},\quad \hat{y}2 = \frac{ \exp(o_2)}{\sum_{i=1}^3 \exp(o_i)},\quad \hat{y}3 = \frac{ \exp(o_3)}{\sum_{i=1}^3 \exp(o_i)}. 
$$

In [29]:
y_hat

tensor([[0.1000, 0.5000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.6000, 0.2000, 0.3000]])

In [30]:
y_hat.exp()

tensor([[1.1052, 1.6487, 1.3499],
        [1.1052, 1.2214, 1.3499],
        [1.8221, 1.2214, 1.3499]])

In [33]:
y_hat.exp().sum(dim=1, keepdim=True)

tensor([[4.1038],
        [3.6764],
        [4.3934]])

In [34]:
y_hat.exp() / y_hat.exp().sum(dim=1, keepdim=True)

tensor([[0.2693, 0.4018, 0.3289],
        [0.3006, 0.3322, 0.3672],
        [0.4147, 0.2780, 0.3072]])

In [39]:
import torchvision.datasets as dset
dataset = dset.ImageFolder('/Users/nick/Documents/images_test') #没有transform，先看看取得的原始图像数据
print(dataset.classes)  #根据分的文件夹的名字来确定的类别
print(dataset.class_to_idx) #按顺序为这些类别定义索引为0,1...
print(dataset.imgs) #返回从所有文件夹中得到的图片的路径以及其类别

['cat', 'dog']
{'cat': 0, 'dog': 1}
[('/Users/nick/Documents/images_test/cat/新版notebook样式.png', 0), ('/Users/nick/Documents/images_test/cat/新版notebook样式的副本.png', 0), ('/Users/nick/Documents/images_test/dog/新版notebook样式.png', 1)]


In [43]:
from datetime import datetime

In [46]:
datetime.now().strftime('%s')

'1582878128'

In [54]:
print(time.time())
print(datetime.now().strftime('%s'))
print(int(datetime.now().strftime('%s')))

print(datetime.now().strftime('%S'))

1582878797.579783
1582878797
1582878797
17


In [45]:
import time
time.time()

1582878101.468839

In [51]:
datetime.now().strftime('%s')

'1582878399'

In [52]:
print(type(datetime.now()))

<class 'datetime.datetime'>
